# Generated by Django 2.2 on 2019-04-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='about',
            field=models.TextField(default=''),
        ),
    ]
